### ISSUE TITLE
Use of a Generic Template in State

### ISSUE THREAD

**Issue by WayneHiller** [mrpmorris/Fluxor#110]
Is there a way to use a generic template in state?

```
public class MyState<T>
{
      public IEnumerable<T> Items { get }
      .....
}
```
I tried it and ran into an issue with the Feature because Fluxor creates those automatically.

**Comment by ashern** [comment]
I also would like to accomplish this. The problem is in instantiating any reducers/effects that refer to templated objects.

I had previously come close to a solution by creating a generic parent class for my reducers (i.e. BaseReducer<T>), and then defining specialized subclasses for any types I'd like to use with that state (i.e. Object1Reducer:BaseReducer<Object1> ... ).

That worked fine until optimizations were made to object creation post v3.2. I haven't tracked down the specific issue introduced there.

+1 for this use case.

**Comment by mrpmorris** [comment]
When searching for features / reducers / effects, Fluxor will exclude any that are part of a Middlewar (e.g. the routing middleware). It will only include them if you add the middleware. So, for example.

If you had this

```
namespace MyApp.Store.SomeUtilClasses
{
  class FakeMiddleware: Middleware {}
}
```

Then Fluxor will not auto-create anything in `MyApp.Store.SomeUtilClasses` or any namespaces below that.

Does that help?

**Comment by WayneHiller** [comment]
I am not using any middleware in the Store.

Has Fuxor been designed for or tested using generics?

```
public class MyState<T>
{
      public IEnumerable<T> Items { get }
      .....
}

public class SomeAction
{
      .....
}

[ReducerMethod]
public static State<T> ReduceSomeAction<T>(State<T> state, SomeAction action) => { .... }
```

Everything compiles ok but when I call Dispatcher.Dispatch(new SomeAction());  ReduceSomeAction is never called.

**Comment by ashern** [comment]
This isn't middleware related. Fluxor doesn't currently support state with a generic type.

`public class ErrorFeature<T> : Feature<SomeState<T>>
    {
        public override string GetName()
        {
            return "ErrorFeature";
        }

        protected override SomeState<T> GetInitialState()
        {
            return new SomeState<T>();
        }
    }`

Compiles but errors on launch:

`[2020-10-06T21:59:07.302Z] Error: System.MemberAccessException: Cannot create an instance of xxx.xxx.ErrorFeature`1[T] because Type.ContainsGenericParameters is true.`

You get similar errors if you try to include a generic type in a defined effect or reducer (although reducers may simply not fire at this point in the codebase, not positive past 3.2).

**Comment by WayneHiller** [comment]
Ya I got that error on the Feature so I hard coded it to a type to keep testing. The Reducer errors seem to be hidden, it just never gets called. Are there are any plans to support generics? I can do it without them but it will mean a lot of duplicate code.

I will dig through the code to try and figure out why it does not work

**Comment by WayneHiller** [comment]
Although I like Fluxor it might be easier for me to just use DI directly

**Comment by mrpmorris** [comment]
I didn't mean Middleware was the problem, it's also a way of stopping reducers etc from being auto registered so you can use them as a base.

As for your requirement. Can you give me some details about what you want to achieve (rather than how you are trying to achieve it with generics)?

Perhaps a concrete example of how you would have to write something without generics and how you'd like to write the same reducers etc with them?

**Comment by WayneHiller** [comment]
I have an app that has a lot of GRUD pages that consist of a page with a  Grid (Table) and then view and edit pages. When the user clicks a row in the Grid it displays a View or Edit page. when they go back to the Grid page I want to restore everything.

The Grid State has data like:

```
    public bool IsLoading { get; set; }
    public GridState<T> GridState { get; set; }
    public DataEnvelope<T> Data { get; set; }
    public int ScrollPos { get; set; }
    public int Page { get; set; }
    public DataSourceRequest Request { get; set; }
```

The Grid component I am using requires a model type (The class Type of the data) that's why I need the Generic Type.

I also need an Effect to load the data and it also needs to specify the Data Type.

```
	public class FetchDataActionEffect : Effect<FetchDataAction>
	{
		private readonly NavigationManager NavMgr;

		public FetchDataActionEffect(NavigationManager navMgr)
		{
			NavMgr = navMgr;
		}

		protected override async Task HandleAsync(FetchDataAction action, IDispatcher dispatcher)
		{
			var result = await NavMgr.BaseUri
								.AppendPathSegment("contact/fetch")
								.PostJsonAsync(action.Request)
								.ReceiveJson<DataEnvelope<NEED DATA TYPE>>();
			dispatcher.Dispatch(new FetchDataResultAction(result.Data, result.TotalCount));
		}
	}
```

And some other actions:

```
public class SaveGridStateAction<T>
{
	public GridState<T> State { get; }
	public SaveGridStateAction(GridState<T> state)
	{
		State = state;
	}
}
```

I don't think it would be productive to duplicate all the code for every Grid in the app.

I was also looking at your friends Blazor-state lib, it might work for this because everything is contained within the State class. I could create a Grid base class with the generic type and then a derived class for each Grid page.

```
public class GridState<T>
{
     .....
}

public class ContactState : GridState<Contact>
{
     ....
}
```

**Comment by ashern** [comment]
I have the same use case, more or less. I have a bespoke grid that requires a type argument, and also actions/effects that are common to the grid regardless of the type. I'd suspect the pattern of injecting a type argument into a component is relatively common.

**Comment by WayneHiller** [comment]
It looks like the Blazor-state lib has the same kind of issue. When you derive from a base class that has a Generic type the Actions stop working.

```
public partial class GridState<T> : State<GridState<T>>
{
....
}

public partial class ContactState : GridState<Contact>
{
}
```

I guess it all has to do with how the Assemblies are scanned for Actions/Handlers etc.

**Comment by ashern** [comment]
That is essentially the approach I use, and it works in v3.2 and previous.

Instead of explicitly defining a specialized state class, I specialize in the feature class.

`public class Feature:Feature<GridState<SomeType>>`

**Comment by mrpmorris** [comment]
@ashern can you give me repro app that works in 3.2 but not later versions?

**Comment by mrpmorris** [comment]
@WayneHiller If you resolve IStore you can call AddFeature AddEffect etc to add instances.

You can also call AddReducer on your Feature instance.

Does that solve the problem?

**Comment by WayneHiller** [comment]
@mrpmorris  Do you have any examples of doing that?

**Comment by ashern** [comment]
@mrpmorris I tried to throw together a quick example for you, but the project is throwing the "Could not find 'tryInitializeFluxor'" error. Never run into that in the past, but I saw another issue recently reference it.

https://github.com/ashern/fluxor_generic

I'll see if I have more time to troubleshoot later, but I'd expect that project to demonstrate the 3.2+ version regression.

The IncrementCount\<T\> action should call the appropriate reducer.

**Comment by WayneHiller** [comment]
@ashern That's a big help. So this same project will not work when switched to Fluxor 3.7.0?

**Comment by ashern** [comment]
@WayneHiller Correct - there was a pull request to speed up type discovery in 3.3 that resulted in the change, I believe

**Comment by WayneHiller** [comment]
I think the only way to figure out why is to clone the repo and step through the code to see what is happening.

**Comment by mrpmorris** [comment]
That helped, thanks. I've found the problem and will fix it.

It looks suspiciously as though you are storing items in a shared list somewhere (for example, a shared list of Customer, a shared list of PurchaseOrder, etc) - is that true?

If so, I cannot recommend against this strongly enough. I would say it's a Flux anti-pattern.

My preferred approach is that the state for a Person (for example) should be replicated for every feature (user task) that requires it, then when you navigate away from that task or it is completed you can clear down its state. If another part of the system updates Persion 1 then your reducers will detect that and update your localised copy's state.

Otherwise, you end up with an ever-growing collection of data that you can never clear out because you have no idea if it is being used somewhere or not. This also means that if someone else deletes an item from the DB then the only way you can know to remove that instance from your shared state unless you have the server tell you what has been deleted.

**Comment by mrpmorris** [comment]
The fact that it worked before was purely accidental. I've looked at what it was doing and reproduced that behaviour in 3.8, so it is now an officially supported feature.

I've tested it with your app and it works fine. You can use the pre-release version if you wish (it seems very stable), the version is 3.8.0-beta-1

**Comment by WayneHiller** [comment]
@mrpmorris I agree that saving a list in shared state is not the way to go, it was really just test code. I will give the new version a try. You bring up a good point about state lifetime. I need to save grid state in each module and then use it when a user comes back to the listing page (scroll pos, current page, sort etc). Go to listing page, click a record to view/edit that record in a new page, then return to the listing. The trouble tho is that state will live in memory as long as the app runs even tho the user may never go back to the listing. I guess it would be ok as long as the amount of state is kept small.

**Comment by ashern** [comment]
Good stuff - thank you @mrpmorris. This library/pattern w/ Blazor is my favorite GUI paradigm of the last 20 years.

**Comment by mrpmorris** [comment]
@WayneHiller Have a list of URL patterns that qualify as being in the same area of the app that won't clear it down, otherwise clear it in a reducer.

You could even set a timer to clear it in X minutes so they have some time limit in unrelated areas, and cancel the timer in the effect if they return.

If it uses a lot of memory there are tricks :)
