### ISSUE TITLE
Lazy loaded modules

### ISSUE THREAD

**Issue by mrpmorris** [mrpmorris/Fluxor#127]

**Comment by mrpmorris** [comment]
Won't do. Unable to resolve instances that are dynamically loaded because they weren't registered in ServiceCollection before the ServiceProvider was created.

**Comment by jimitndiaye** [comment]
I know this issue has been closed but I kind of need it for my scenario. 
Assuming you are able to dynamically resolve the IFeature and IEffect instances and call ```IStore.AddFeature``` and ```IStore.AddEffect``` respectively, will they immediately start receiving actions or is there some other setup necessary? I ask because I am doing excactly that but actions are not being dispatched to the added effects and features (and their inherent reducers).

**Comment by mrpmorris** [comment]
You can only dynamically load them and have them scanned before creating the store, you cannot add them afterwards.
