### ISSUE TITLE
Guidance needed on correct usage of UI/Business logic

### ISSUE THREAD

**Issue by danglingneuron** [mrpmorris/Fluxor#136]
In a big LOB application, we have inter-dependent modules that may share parts of data / state and are pulling and pushing data to a service tier and then database. The front end does have UI logic, and some minimal business logic.
For strictly UI logic that has to do with a specific view only, it could be written in the razor code-behind. Also, if there is an Edit form and has basic and complex validation rules, that could be written in the code behind as well before dispatching an action. However some logic may be shared across views/modules. 

One way would be to add logic/functions (or decision getter properties) to the State classes, pro: the logic stays with the state, con: state should be pure state. These functions could be used/called from the view or from the reducers based on the nature of the logic - the functions themselves don't change state understandably, they just give us decisions. 

Another way would be to use extension methods on the state or have a separate logic service that receives state object and provides decisions. This could be used in the view or in the reducer. However the docs say reducers should be plain reducers with no DI which makes sense.
Any other options? 

A related design issue is if a state should just be a small vertical slice (state per view / use case only) and some central app state for shared stuff?  or a big state class per module (10s of use cases)?

Fluxor/Redux is a new pattern for me so I am just trying to see what the right way to do these things are so I can create a list of best practices for all developers on the team.

**Comment by padnom** [comment]
Fluxor is a powerful librarie. 
I'm also stuck indeed in a big clean architecture project. 
I would like to use fluxor in an separate librarie.
Should I put into UI ring or Use Case ring...
How to inject an IState<CounterState>

**Comment by Dmo16** [comment]
I am working on a few different projects right now that may help shed a bit of light for you.

First up, this article, and its second part helped me a ton in terms of arranging implementation, if you haven't read them, I highly suggest it: 

https://betweentwobrackets.dev/posts/2020/06/state-management-with-blazor-using-fluxor-part-1/

I'll try and address things in order of your post: 

For validation, I strongly suggest @mrpmorris' [blazor-validation](https://github.com/mrpmorris/blazor-validation) package which implements fluent validation and is extremely easy to use for both simple and complex validation.

This would remove your validation concerns from the code behind and clean that up a bit, also removing the concern of validation logic being shared across components(views).

"Another way would be to use extension methods on the state or have a separate logic service that receives state object and provides decisions....
....Any other options?"

There are many ways you can do this but the way I've found to be the simplest to implement is to write base component classes with the properties you need on them, and inherit from there.

Example, a form class could have standard props like `protected bool CancelSubmit` or other things you need, like user state.

This is also where you would inject whatever state you needed, like user or, if the form is pulling double duty as an edit option, you can set the form's EditContext model to be whatever object the user is trying to edit by passing that state to the components on initialization.

You can also just write some helper methods and call them from these component bases, that way they're decoupled from your UI, and not in the store anywhere, but can still be called from both.

"A related design issue is if a state should just be a small vertical slice (state per view / use case only) and some central app state for shared stuff? or a big state class per module (10s of use cases)?"

I have had to play with this myself recently and with some advice from senior engineers, the bottom line seems to be that you decide what rules you need to play by.

There are cases where a "DTO" style state object makes sense, since you may be loading all relevant info at once, and other times where you're only needing a small slice of that state, so it makes more computing sense to only have that piece of state.

State itself is essentially central, as you are injecting the state objects that you need access to, into whatever components need them, so in basically what you would need to decide is whether you want one large state object that houses many, smaller states, or a state per model/object.

I personally find it easier to keep things as split up as possible for granularity, but of course, to each their own.

One last thing, I have several forms that are composed of more than one component, and rely on that other component's info for submission.

The way I have handled this is to have Component A house injected state of Component B's model, and listen for changes.

Whenever Component B is manipulated, state is updated in the store by dispatching a new "set" action. Component A now has the latest info from Component B, and I ingest that into Component A's submission logic.

I hope my ramblings help some!

P.S. If you take nothing else from the article I posted at the beginning of this information onslaught, do yourself a favor and absolutely use the "StateFacade" idea. Saves tons of headaches.

**Comment by padnom** [comment]
Thanks for taking the time to answer 
I will read all the posts.
I hope this will take away my doubts.
If you have an example how you implement it. It will be a pleasure to read it. 
Regards
