### ISSUE TITLE
How to implement multiple components with their own instance of the same state?

### ISSUE THREAD

**Issue by iButters** [mrpmorris/Fluxor#197]
For example: 
How can i add multiple counters (from the tutorial), each one with its own instance of the same state?

I am new to Blazor and Fluxor and sadly there are not many resources related to Fluxor for Blazor. So i am having a hard time to find an answer.

**Comment by mrpmorris** [comment]
You can make your feature state an IReadonlyDictionary of key/state.

Instead of descending from FluxorComponent (which will render when any counter staye changes) subscribe to the StateChanged event on your injected state so you can check if your entry has changed in order to render.

Make sure you implement IDisposable in your component and unsubscribe.

**Comment by dotnetshadow** [comment]
Is it possible to have an example of this?
