### ISSUE TITLE
Discussion: how to make code more compact

### ISSUE THREAD

**Issue by hillin** [mrpmorris/Fluxor#203]
We are exploring the best practices to design Fluxor code blocks. The goal is to make the code more compact and more boilerplate-free. Here are some thoughts and questions:

# Features
- (1.1) Is it possible that state and feature can form a one-to-many or many-to-one relationship (e.g. a state used by many features); or are they always locked to a one-to-one relationship?
- (1.2) If they are always one-to-one, is it possible to automatically generate features for states (e.g. by decorating the state class with a `StateFeatureAttribute`)? Because all the feature classes we've written only function to provide a name (by returning the `nameof` the state class) and a default state value (which we always provide in the default constructor), they seem quite redundant.
- (1.3) Or at least we can have a code snippet to create a state + its corresponding feature, with only a few key strokes.

# Actions and Reducers
- (2.1) We define actions as nested classes within the state class. We avoid sharing actions between states. 
- (2.2) We define reducers as static methods within the state class, *if* the reducer only affects the state it resides. All the reducers defined this way have the same name `Reduce`, distinguished only by their `action` parameter.
E.g.
```c#
public record CounterState(int Value)
{
    public record IncrementCounterStateAction(int Increment) {}

    [ReducerMethod]
    public static CounterState Reduce(CounterState state, IncrementCounterStateAction action)
    {
        return state with
        {
            Value = state.Value + action.Increment
        };
    }
}
```
This way we can make a code snippet to generate an action and its reducer stub easily.
(2.3) Do you think this is a good practice? Could it lead to any unexpected problem?

# Effects
- (3.1) I understand effects have a distributive nature, i.e. the effect class can be defined far away from the action class which triggers it. However 9 out of 10 times in our code the effects are only used to handle async loading; they are always defined aside of the actions. This has created quite a bit of boilerplate code which follows a distinctive yet common pattern.

```c#
public record StartSearchAction(string SearchText) {}
public record SearchResultAction(SearchResult SearchResult) {}
public class StartSearchActionEffect : Effect<StartSearchAction>
{
    public override async Task HandleAsync(StartSearchAction action, IDispatcher dispatcher)
    {
        var result = await this.SearchAsync(action.SearchText);
        dispatcher.Dispatch(new SearchResultAction(result));
    }

    private Task<SearchResult> SearchAsync(string searchText)
    {
        throw new NotImplementedException();
    }
}
```
This, again, can be offloaded to code snippets. However it still bloats the codebase, especially when you strictly follow a one-type-per-file convention like us. 

We all understand that these are the bare minimum code blocks for the flux pattern to work here, because effect is the only place you can inject services. One possible option is define the `SearchResultAction` and the `StartSearchActionEffect` as nested classes of the `StartSearchAction` class:
```c#
public record StartSearchAction(string SearchText)
{
    public record SearchResultAction(SearchResult SearchResult) { }
    public class StartSearchActionEffect : Effect<StartSearchAction>
    {
        public override async Task HandleAsync(StartSearchAction action, IDispatcher dispatcher)
        {
            var result = await this.SearchAsync(action.SearchText);
            dispatcher.Dispatch(new SearchResultAction(result));
        }

        private Task<SearchResult> SearchAsync(string searchText)
        {
            throw new NotImplementedException();
        }
    }
}
```
(3.2) Do you think this is a good practice? Could it lead to any unexpected problem (can fluxor detect effects in nested classes)?
(3.3) Any other idea to reduce the syntactical noises in this kind of async loading pattern?

**Comment by ducman** [comment]
I'm in the same boat in terms of trying to find that nice organizational pattern that is readable, maintainable, etc. I think we may be in the minorities as a lot of google searches shows people group things in folders, etc. (Actions, Reducers, etc.) like the redux way which I'm not a big fan of anymore. I use to but now I'm going more with a Vertical Slice Architecture approach (i.e nested classes) to keep unit of work isolated/together.

I agree 100% with `Feature` since it's the same code every time I create them. The reason why a lot of these boilerplate codes are needed is `State` is just a class and it has no base interface type for Fluxor to detect them. That's why `Feature<State>` is needed (and probably other reasons as well).

Here are examples that I have tried which may fall in line with your post. Please note I'm only trying to show structure here:

```cs
public class UserStore
{
	public record State(bool IsLoading = false, string ErrorMessage = null, IEnumerable<User>> Users = null)
		: RootState(IsLoading, ErrorMessage);

	public class Feature : Feature<State>
	{
		public override string GetName() => GetType().DeclaringType.Name;
		protected override State GetInitialState() => new();
	}

	#region Get Users
	public record GetUsersAction(int CompanyId)
	{
		[ReducerMethod]
		public static State Reduce(State state, GetUsersAction_)
			=> state with { IsLoading = true };

		public class Effect : Effect<GetUsersAction>
		{
			public override async Task HandleAsync(GetUsersAction action, IDispatcher dispatcher)
			{
				try
				{
                                        var users = await GetUsersAsync(action);  // method not shown here 
					dispatcher.Dispatch(new GetUsersSuccessAction(users));
				}
				catch (Exception ex)
				{
					dispatcher.Dispatch(new GetUsersFailureAction(ex.Message));
				}
			}
		}
	}

	public record GetUsersSuccessAction(IEnumerable<User> Users)
	{
		[ReducerMethod]
		public static State Reduce(State state, GetUsersSuccessAction action)
			=> state with { IsLoading = false, Users = action.Users };
	}

	public record GetUsersFailureAction(string ErrorMessage) : FailureAction(ErrorMessage)
	{
		[ReducerMethod]
		public static State Reduce(State state, GetUsersFailureActionaction)
			=> state with { IsLoading = false, ErrorMessage = action.ErrorMessage };
	}
	#endregion
}
```

or 
```cs
public class UserStore
{
	public record State(bool IsLoading = false, string ErrorMessage = null, IEnumerable<User>> Users = null)
		: RootState(IsLoading, ErrorMessage);

	public class Feature : Feature<State>
	{
		public override string GetName() => GetType().DeclaringType.Name;

		protected override State GetInitialState() => new();
	}

	#region Actions
	public record GetUsersAction(int CompanyId);
	public record GetUsersSuccessAction(IEnumerable<User> Users);
	public record GetUsersFailureAction(string ErrorMessage) : FailureAction(ErrorMessage);
	#endregion

	#region Reducers
	[ReducerMethod]
	public static State Reduce(State state, GetUsersAction_)
		=> state with { IsLoading = true };
	[ReducerMethod]
	public static State Reduce(State state, GetUsersSuccessAction action)
		=> state with { IsLoading = false, Users = action.Users };
        [ReducerMethod]
	public static State Reduce(State state, GetUsersFailureActionaction)
		=> state with { IsLoading = false, ErrorMessage = action.ErrorMessage };
	#endregion

	public class Effect : Effect<GetUsersAction>
	{
		public override async Task HandleAsync(GetUsersAction action, IDispatcher dispatcher)
		{
			try
			{
				var users = await GetUsersAsync(action);  // method not shown here 
				dispatcher.Dispatch(new GetUsersSuccessAction(users));
			}
			catch (Exception ex)
			{
				dispatcher.Dispatch(new GetUsersFailureAction(ex.Message));
			}
		}
	}
}
```

IMHO, the 2nd structure seems cleaner and easier to read. I have custom base classes here and there that are not shown. But I've used both and they work fine. In terms of best practice, I'll defer to the pros. I'm still new to Fluxor and need more implementations to see if there is a cleaner way to organize things.

**Comment by hillin** [comment]
Thanks @ducman. Your approaches can definitely make the code more organized and domain-oriented, but to me both of them are using nested classes instead of namespaces (or in most cases, folders). The boilerplates are still there, nothing is really simplified.

**Comment by hillin** [comment]
These days I'm coming to the idea that maybe we need a DSL to make this job more elegantly done. For example, we could have a razor-style file (aye aye I know this is a weird choice, I'll explain later):
```razor
<State Name="SearchState">
    <Property Type="bool" Name="IsSearching" DefaultValue="false" />
    <Property Type="string?" Name="Keyword" DefaultValue="null" />
    <Property Type="SearchResult[]?" Name="SearchResult" DefaultValue="null" />

    <Action Name="SearchResultAction">
        <Property Type="SearchResult[]" Name="SearchResult" />
        <Reducer>
            @(state, action) => {
                state with {
                    IsSearching = false;
                    SearchResult = action.SearchResult;
                }
            }
        </Reducer>
    </Action>

    <Action Name="StartSearchAction">
        <Property Type="string" Name="Keyword" />

        <Reducer>
            @(state, action) => {
                state with {
                    IsSearching = true;
                    Keyword = action.Keyword;
                    SearchResult = null;
                }
            }
        </Reducer>

        <Effect Name="StartSearchActionEffect">
            <Handle>
                @async (action, dispatcher) => {
                    Task<SearchResult> SearchAsync(string keyword)
                    {
                        throw new NotImplementedException();
                    }
                    var result = await SearchAsync(action.Keyword);
                    dispatcher.Dispatch(new SearchResultAction(result));
                }
            </Handle>
        </Effect>
    </Action>
</State>
```

Of course the XML syntax is cumbersome and has been hated for years, but with razor files we may utilize the great intellisense support of Visual Studio (because there are quite a bit of C# code involved). It's also very easy to parse (we may use [RazorEngine](https://github.com/Antaris/RazorEngine)). Code generation could be done with [C# Source Generators](https://devblogs.microsoft.com/dotnet/introducing-c-source-generators/).

**Comment by mrpmorris** [comment]
> (1.1) Is it possible that state and feature can form a one-to-many or many-to-one relationship (e.g. a state used by many features); or are they always locked to a one-to-one relationship?

A feature can only have one state, the same state may be used by many features. However, I would question my design if I were doing this. Features should really be a use-case, you shouldn't need to have the same use case more than once.

> (1.2) If they are always one-to-one, is it possible to automatically generate features for states

How would I determine what the default state values are?

>  Or at least we can have a code snippet to create a state + its corresponding feature, with only a few key strokes

I wouldn't want to do that because people like to name things in different ways, and it's easy for you to make your own code snippet in a minute or two.

> (2.1) We define actions as nested classes within the state class. We avoid sharing actions between states.

The C# compiler warns against public nested classes. Instead, put them in a namespace that it specific to the state.

It is very likely though that there will eventually be one action that multiple states must react to. For example, if you are creating an email (CreateEmailFeature) and you click Send, then the SidebarFeature that shows read/unread/sent folders with totals will need to alter.

Or if you are creating a new email and then edit the contact's name (EditContactFeature) then you'll want your CreateEmailState to update to reflect that change.

My rules of thumb these days are

1. Have all actions in a single namespace, so that any state can be affected by it without having to reference the namespaces of other states.
2. Only have action specific to your use-case (feature) namespace if you need to call an async service as a result of user interaction. For example, if editing a postal address, when the user selects a country you call a server to get a list of states/regions for the next dropdown box. This is purely a user-interaction experience, not a notification to the app that there is a new "record of truth" (a customer's name is now different / the number of sent emails has now changed).
3. Otherwise, I don't use state. The UI doesn't need to be 100% driven by actions and reducers if no async calls are involved. Just let the UI component be an agnostic UI component as much as possible. If user inputs aren't considered the latest truth about your state until after you save them then you don't need to touch the store at all. If the user changing options etc should immediately affect the behaviour of the app, then you would just commit the state to the store whenever they change something (and perhaps only update a server if they click the save button).

> (2.2) We define reducers as static methods within the state class, if the reducer only affects the state it resides.

I don't see a problem with that as long as the reducer methods are always static - which (in my opinion) they should be anyway.

> (3.1) However 9 out of 10 times in our code the effects are only used to handle async loading; they are always defined aside of the actions.

Again, nested public classes seem to be frowned upon - because you are just effectively making a namespace with the same name as a class.

Instead I would recommend having a MyStateEffects class and using effect methods instead of descendants of Effect<T> (explained after next point)

> This has created quite a bit of boilerplate code which follows a distinctive yet common pattern.

Change
```
public class StartSearchActionEffect : Effect<StartSearchAction>
    {
        public override async Task HandleAsync(StartSearchAction action, IDispatcher dispatcher)
        {
            var result = await this.SearchAsync(action.SearchText);
            dispatcher.Dispatch(new SearchResultAction(result));
        }

        private Task<SearchResult> SearchAsync(string searchText)
        {
            throw new NotImplementedException();
        }
    }
```

To

```
public class WhateverStateEffects
{
  private readonly ISomeDependency SomeDependency;
  public WhateverStateEffects(ISomeDependency someDependency)
  {
    SomeDependency = someDependency;
  }

  [EffectMethod]
  public async Task Handle(SearchAction action, IDispatcher dispatcher)
  {
    DependencyResultType result = await SomeDependency.Search(action.Text);
    dispatcher.Dispatch(new SearchActionResult(result.Items);
  }

  [EffectMethod]
  public async Task Handle(SomeOtherAction action, IDispatcher dispatcher)
  {
    SomeOtherResultType result = await SomeDependency.DoSomethingElse(action.Whatever);
    dipatcher.Dispatch(new SomeOtherActionResult(result.Whatever);
  }

  // etc
}
```

As you can see, it is a lot less work.

**Comment by hillin** [comment]
Thanks @mrpmorris for the great insights.

> >(1.2) If they are always one-to-one, is it possible to automatically generate features for states

> How would I determine what the default state values are?

Maybe simply use `Activator.CreateInstance` and use whatever the default values are? I'm not saying that `Feature`s should be removed, if the default value must be specified by a feature, write a feature; otherwise the default constructor of the state should be responsible to set the default values. It's a convention over configuration thing.

> The C# compiler warns against public nested classes. Instead, put them in a namespace that it specific to the state.

Good point. However we also enforces a strict one-type-per-file convention (but not as strict for nested types), so instead of having a whole bunch of one-liner files, we chose to suppress that warning instead. Plus with in a state class, we can take advantage of the [ClassName](https://docs.microsoft.com/en-us/visualstudio/ide/code-snippet-functions?view=vs-2019#classname-example) function of the code snippet to generate the state type name automatically. Not the best code of conduct tho, I agree.

The rest part about states and actions are also very inspiring.

On the effects, I didn't know the `EffectMethod` attribute was a thing. It can definitely make the code cleaner in certain scenarios (save up some effect classes). However what I'm more concerned about is the code blocks required to perform a simple yet very common async loading pattern: a start action, an effect, a result action and an error action, plus 3 reducers for these actions. For an UI full of async loaded data, this is overwhelmingly verbose.

One idea to reduce this verbosity is to create a base effect like this (not yet tested, not sure if it works):
```c#
public abstract class AsyncLoadingEffect<TTriggerAction, TData> : Effect<TTriggerAction>
{
    public override async Task HandleAsync(TTriggerAction action, IDispatcher dispatcher)
    {
        try
        {
            var data = await this.LoadAsync(action);
            dispatcher.Dispatch(new SuccessAction(data));
        }
        catch (Exception ex)
        {
            dispatcher.Dispatch(new FailureAction(ex));
        }
    }

    protected abstract Task<TData> LoadAsync(TTriggerAction action);

    public class SuccessAction
    {
        public SuccessAction(TData data)
        {
            this.Data = data;
        }

        public TData Data { get; }
    }

    public class FailureAction
    {
        public FailureAction(Exception exception)
        {
            this.Exception = exception;
        }

        public Exception Exception { get; }
    }
}
```
So we can inherit from it and abstract off at least some actions:
```c#
public class StartSearchActionEffect : AsyncLoadingEffect<StartSearchAction, SearchResult[]>
{
    protected override Task<SearchResult[]> LoadAsync(StartSearchAction action)
    {
        throw new NotImplementedException();
    }
}
```
Still we'd like to have a, say, `AsyncLoadedState` base class which has an `IsLoading`, a `LoadErrorMessage` and a `Data` property. This is definitely doable, but using record diminishes the benefit of such code reusing; plus automatic reducing of the `SuccessAction` and the `FailureAction`, which does not seem possible in Fluxor's design without a code generator.

Overall, I think most of the issues here are a classic convention or configuration debate. I understand that Fluxor wants to be flexible, leave all the possibilities open and up to the developers to decide how to use it; but it also makes common daily tasks cumbersome, which does nothing good for code quality and maintainability. I hope that based on the great configurability, we can have some conventional designs to make using it easier and more relaxed.

**Comment by ducman** [comment]
@mrpmorris, I like your 'rules of thumb' which I'll take and move things around. Do you have examples of when a state is used by many features? Thanks for considering the `FeatureAttribute`.

@hillin, I see where you're going with the `AsyncLoadingEffect` which was what I was going to clean up next. The caution I have here is that if you're using the ReduxDevTools, the action class name is what's displayed; so it may get confusing if you see SuccessAction, etc. multiple times even though it's for different effects. I'm unsure if there is a way to override the action name for the ReduxDevTools. I agree with you; the apps I deal with all make numerous calls to webapis, having these 3 actions (loading, success, failure) and reducers do get annoying since they all do similar things for every effect.

**Comment by hillin** [comment]
> I'm unsure if there is a way to override the action name for the ReduxDevTools.

The action names are [generated by Fluxor](https://github.com/mrpmorris/Fluxor/blob/ed06a656ce48b06ff584d82462b521bb58e8db20/Source/Fluxor.Blazor.Web.ReduxDevTools/ActionInfo.cs#L17) so we will eventually find a way to override it.

**Comment by mrpmorris** [comment]
@ducman I don't think state should ever be used by more than one feature.

**Comment by mrpmorris** [comment]
This now works. I will do a release once I have written some unit tests.

```
    [Feature(name: "Counter", getInitialStateMethodName: nameof(GetInitialState))]
    public class CounterState
    {
        public int ClickCount { get; }

        private static CounterState GetInitialState() => new CounterState(0);

        public CounterState(int clickCount)
        {
            ClickCount = clickCount;
        }
    }
```

**Comment by ducman** [comment]
Awesome @mrpmorris. Do you know if the below would also work?

```cs
[Feature]
public record CounterState(int ClickCount = 0);
```
I would say the name if not given is `CounterState`, and the initial state is in the default ctor when doing `new()`.

**Comment by hillin** [comment]
I prefer the `FeatureAttribute` to be a simple shorthand instead of actually writing a feature class, rather than a replacement; so it can simply rely on the default constructor to provide the default state value. If someone ever found they need to specify a different default value, they write a feature class. Using a string name for `getInitialStateMethodName` is less desirable to me, because the contract is not enforced at compile time.

Or maybe we can use interface instead of attribute. This way we may be able to take advantage of the [static interface members](https://github.com/dotnet/csharplang/issues/4436) feature one day, if it come to reality eventually.

**Comment by mrpmorris** [comment]
If you use nameof then it is checked when compiling, and changed when refactoring.

**Comment by hillin** [comment]
> If you use nameof then it is checked when compiling, and changed when refactoring.

I mean the signature of the method, its parameters (parameterless), its return value etc.

**Comment by mrpmorris** [comment]
You can't declare static members in a  interface.

**Comment by hillin** [comment]
Yes sir, but as I stated, [maybe in the future](https://github.com/dotnet/csharplang/issues/4436)

**Comment by hillin** [comment]
Now we have https://github.com/mrpmorris/Fluxor/issues/204 now, plus I'm not expecting more momentum on the other topics in this issue here, I'm closing this one.
