### ISSUE TITLE
FluxorOptions.AfterScan callback

### ISSUE THREAD

**Issue by mrpmorris** [mrpmorris/Fluxor#401]
Consider adding a callback that is called after all features have been discovered, so the developer can programmatically register generic actions / effects / reducers.

**Comment by gingters** [comment]
Please also consider registering Fluxor without any automatic scanning for types at all.

I would really like to explicitly list all state types as well as explicitly list the classes that provide reducer methods as well as effects.

That way we could provide different effect implementations based on the host type (Blazor Server, Blazor WASM, Hybrid...), but still provide all implementations in the same library.

Also, maybe we have a feature in a shared library that should be registered in certain apps, but not in the current one.
Configuring Fluxor discovery to explicitly omit these is a bit counter-intuitive for the normal way ASP.NET Core DI works, and also error-prone because you need to touch all other projects using your library that should not have a feature enabled to remove it from discovery. I really only want to add a feature to a project when I need it.

I'd love to have an API for that like this:
```
services.AddFluxor()
   .AddState<MyFeatureStateType>()
   .AddReducers<MyFirstReducerType>()
   .AddReducers<MySecondReducerType>()
   .AddEffects<MyBlazorWasmEffectType>()
```

**Comment by gingters** [comment]
@mrpmorris  Would you be willing - in general - to accept a PR for an API like that to register states, reducer types, even individual reducer methods and effect types as well as individual effect methods individually without the need for auto-discovery?
