### ISSUE TITLE
Dispatch from Polly 

### ISSUE THREAD

**Issue by Hantse** [mrpmorris/Fluxor#470]
Hello.

I try to implement in my application a generic handler for HTTPClient.
I used Polly and a Policy to dispatch an action (for 200, 400 etc) the main flow work well, but action dispatched in the Polly, it's not catch by reducers, any idea?

Kr,

**Comment by mrpmorris** [comment]
I don't know why, but reducers should never need Polly.

Your reducer code should always work. If it fails then it's because of a bug that needs fixing. Polly is for transitive errors like network outages - your reducers definitely shouldn't be doing stuff with the network.

If you call it to external resources then you can use Polly, but this should never be done in a reducer. It should either be in your application code or an Effect (if you choose to use them).

**Comment by Hantse** [comment]
Hello, 
Thx for response. 

The dispatcher is call from retry policy from Polly.
To dispatch status on page and display message globally on layout.

But, event dispatch from Polly, it's never received by Reducers.

Kr,

**Comment by mrpmorris** [comment]
Please show me some code

**Comment by mrpmorris** [comment]
Closing this. Let me know if you have something for me.
