### ISSUE TITLE
Dispatching action in effect - running orders

### ISSUE THREAD

**Issue by alperenbelgic** [mrpmorris/Fluxor#472]
I dispatch `LoginSubmittedAction` in a component, and in the effect method I dispatch `LoginAction`. 

I was expecting to see

>  _login action dispatch completed_

 log woud be written as last log. but it works before LoginAction's reducer and effect. 

is this the expected behaviour?

( the reason I have multipe actions is that I'd like to isolate the behaviour in LoginAction to reuse somewhere else. 

<img width="541" alt="image" src="https://github.com/mrpmorris/Fluxor/assets/1174835/efd6b2b5-1e37-4f7c-890b-cd9bf53e6073">

![image](https://github.com/mrpmorris/Fluxor/assets/1174835/44cd83bd-22ba-400b-a60a-e1b656a53870)

**Comment by stagep** [comment]
It appears that you are dispatching to an effect within an effect so essentially calling an async method within an async method. There is no guarantee of order because the async method called from your async method could complete before or after the next line of code. Use an effect for calling an async method like an API and then dispatch an action that is handled by a reducer and updates the state.
